title: [Giovanni Pecorino's Portfolio]
description: [Here you will find data analytic projects that I have completed as well as links to their respective repositories that contain full breakdowns of the project and all code used in them.]
theme: jekyll-theme-slate
google_analytics: G-8PKKMKVXRP
