title: [Giovanni Pecorino's Portfolio]
description: [Here you will data analytic projects that I have completed as well as links to their respective repositories that contain full breakdowns of the project and all code used in it.]
theme: jekyll-theme-cayman
